apiVersion: v1
kind: Service
metadata:
  name: rabbit-svc
spec:
  selector:
    app.kubernetes.io/name: triple-rabbit
  ports:
    - name: management
      port: 15671 #15671 com TLS e 15672 sem TLS
      targetPort: 15671
    - name: rabbit
      port: 5671 #5671 com TLS e 5672 sem TLS
      targetPort: 5671
    - name: inter
      port: 15691 #15691 com TLS e 15692 sem TLS
      targetPort: 15691
  type: LoadBalancer