apiVersion: v1
kind: Service
metadata:
  name: rabbit-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: triple-rabbit
  ports:
    - name: management
      port: 15671
      targetPort: 15671
      nodePort: 30001
    - name: rabbit
      port: 5671
      targetPort: 5671
      nodePort: 30002
    - name: inter
      port: 15691
      targetPort: 15691
      nodePort: 30003